// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA14f_gqNYwMwD7S5NBsNukIliRGkrZdxw',
    appId: '1:669874258100:web:f9b296c33bf5171ef2d7e1',
    messagingSenderId: '669874258100',
    projectId: 'clipit-a0c32',
    authDomain: 'clipit-a0c32.firebaseapp.com',
    storageBucket: 'clipit-a0c32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_28f112rkDNppVhaA-Ig4cd4g1SbEa4',
    appId: '1:669874258100:android:c626ea8107a533fcf2d7e1',
    messagingSenderId: '669874258100',
    projectId: 'clipit-a0c32',
    storageBucket: 'clipit-a0c32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDruaas-I98QFrbfZgma0rsvSDgErbZ8',
    appId: '1:669874258100:ios:8d70a098acd9362cf2d7e1',
    messagingSenderId: '669874258100',
    projectId: 'clipit-a0c32',
    storageBucket: 'clipit-a0c32.appspot.com',
    iosBundleId: 'com.example.clipit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoDruaas-I98QFrbfZgma0rsvSDgErbZ8',
    appId: '1:669874258100:ios:1a3b54f0bc26dcc7f2d7e1',
    messagingSenderId: '669874258100',
    projectId: 'clipit-a0c32',
    storageBucket: 'clipit-a0c32.appspot.com',
    iosBundleId: 'com.example.clipit.RunnerTests',
  );
}
